In [97]:
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt
%matplotlib inline

import seaborn as sb
sb.set_style('darkgrid')

import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import scale
from sklearn import metrics
from sklearn.metrics import recall_score,accuracy_score,precision_score,classification_report
from sklearn.metrics import confusion_matrix
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [98]:
iris=pd.read_excel('Z:/FA2/Irisdata.xls')
iris

sepal length  sepal width  petal length  petal width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
6             4.6          3.4           1.4          0.3     Iris-setosa
7             5.0          3.4           1.5          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
9             4.9          3.1           1.5          0.1     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
11            4.8          3.4           1.6          0.2     Iris-setosa
12            4.8          3.0           1.4          0.1     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
16            5.4          3.9           1.3          0.4     Iris-setosa
17            5.1          3.5           1.4          0.3     Iris-setosa
18            5.7          3.8           1.7          0.3     Iris-setosa
19            5.1          3.8           1.5          0.3     Iris-setosa
20            5.4          3.4           1.7          0.2     Iris-setosa
21            5.1          3.7           1.5          0.4     Iris-setosa
22            4.6          3.6           1.0          0.2     Iris-setosa
23            5.1          3.3           1.7          0.5     Iris-setosa
24            4.8          3.4           1.9          0.2     Iris-setosa
25            5.0          3.0           1.6          0.2     Iris-setosa
26            5.0          3.4           1.6          0.4     Iris-setosa
27            5.2          3.5           1.5          0.2     Iris-setosa
28            5.2          3.4           1.4          0.2     Iris-setosa
29            4.7          3.2           1.6          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142      

In [99]:
iris.isnull().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
iris            0
dtype: int64

In [100]:
iris['iris'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: iris, dtype: int64

In [101]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal length    150 non-null float64
sepal width     150 non-null float64
petal length    150 non-null float64
petal width     150 non-null float64
iris            150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [102]:
le_iris=LabelEncoder()
le_iris=le_iris.fit(iris['iris'])
iris['iris']=le_iris.transform(iris['iris'])

In [103]:
X=iris.loc[:,['sepal length','sepal width','petal length','petal width']]
y=iris.loc[:,['iris']]

In [104]:
scaler=MinMaxScaler()
nX=pd.DataFrame(scaler.fit_transform(X))

In [105]:
nX.columns=X.columns

In [106]:
nX

sepal length  sepal width  petal length  petal width
0        0.222222     0.625000      0.067797     0.041667
1        0.166667     0.416667      0.067797     0.041667
2        0.111111     0.500000      0.050847     0.041667
3        0.083333     0.458333      0.084746     0.041667
4        0.194444     0.666667      0.067797     0.041667
5        0.305556     0.791667      0.118644     0.125000
6        0.083333     0.583333      0.067797     0.083333
7        0.194444     0.583333      0.084746     0.041667
8        0.027778     0.375000      0.067797     0.041667
9        0.166667     0.458333      0.084746     0.000000
10       0.305556     0.708333      0.084746     0.041667
11       0.138889     0.583333      0.101695     0.041667
12       0.138889     0.416667      0.067797     0.000000
13       0.000000     0.416667      0.016949     0.000000
14       0.416667     0.833333      0.033898     0.041667
15       0.388889     1.000000      0.084746     0.125000
16       0.305556     0.791667      0.050847     0.125000
17       0.222222     0.625000      0.067797     0.083333
18       0.388889     0.750000      0.118644     0.083333
19       0.222222     0.750000      0.084746     0.083333
20       0.305556     0.583333      0.118644     0.041667
21       0.222222     0.708333      0.084746     0.125000
22       0.083333     0.666667      0.000000     0.041667
23       0.222222     0.541667      0.118644     0.166667
24       0.138889     0.583333      0.152542     0.041667
25       0.194444     0.416667      0.101695     0.041667
26       0.194444     0.583333      0.101695     0.125000
27       0.250000     0.625000      0.084746     0.041667
28       0.250000     0.583333      0.067797     0.041667
29       0.111111     0.500000      0.101695     0.041667
..            ...          ...           ...          ...
120      0.722222     0.500000      0.796610     0.916667
121      0.361111     0.333333      0.661017     0.791667
122      0.944444     0.333333      0.966102     0.791667
123      0.555556     0.291667      0.661017     0.708333
124      0.666667     0.541667      0.796610     0.833333
125      0.805556     0.500000      0.847458     0.708333
126      0.527778     0.333333      0.644068     0.708333
127      0.500000     0.416667      0.661017     0.708333
128      0.583333     0.333333      0.779661     0.833333
129      0.805556     0.416667      0.813559     0.625000
130      0.861111     0.333333      0.864407     0.750000
131      1.000000     0.750000      0.915254     0.791667
132      0.583333     0.333333      0.779661     0.875000
133      0.555556     0.333333      0.694915     0.583333
134      0.500000     0.250000      0.779661     0.541667
135      0.944444     0.416667      0.864407     0.916667
136      0.555556     0.583333      0.779661     0.958333
137      0.583333     0.458333      0.762712     0.708333
138      0.472222     0.416667      0.644068     0.708333
139      0.722222     0.458333      0.745763     0.833333
140      0.666667     0.458333      0.779661     0.958333
141      0.722222     0.458333      0.694915     0.916667
142      0.416667     0.291667      0.694915     0.750000
143      0.694444     0.500000      0.830508     0.916667
144      0.666667     0.541667      0.796610     1.000000
145      0.666667     0.416667      0.711864     0.916667
146      0.555556     0.208333      0.677966     0.750000
147      0.611111     0.416667      0.711864     0.791667
148      0.527778     0.583333      0.745763     0.916667
149      0.444444     0.416667      0.694915     0.708333

[150 rows x 4 columns]

In [107]:
iris

sepal length  sepal width  petal length  petal width  iris
0             5.1          3.5           1.4          0.2     0
1             4.9          3.0           1.4          0.2     0
2             4.7          3.2           1.3          0.2     0
3             4.6          3.1           1.5          0.2     0
4             5.0          3.6           1.4          0.2     0
5             5.4          3.9           1.7          0.4     0
6             4.6          3.4           1.4          0.3     0
7             5.0          3.4           1.5          0.2     0
8             4.4          2.9           1.4          0.2     0
9             4.9          3.1           1.5          0.1     0
10            5.4          3.7           1.5          0.2     0
11            4.8          3.4           1.6          0.2     0
12            4.8          3.0           1.4          0.1     0
13            4.3          3.0           1.1          0.1     0
14            5.8          4.0           1.2          0.2     0
15            5.7          4.4           1.5          0.4     0
16            5.4          3.9           1.3          0.4     0
17            5.1          3.5           1.4          0.3     0
18            5.7          3.8           1.7          0.3     0
19            5.1          3.8           1.5          0.3     0
20            5.4          3.4           1.7          0.2     0
21            5.1          3.7           1.5          0.4     0
22            4.6          3.6           1.0          0.2     0
23            5.1          3.3           1.7          0.5     0
24            4.8          3.4           1.9          0.2     0
25            5.0          3.0           1.6          0.2     0
26            5.0          3.4           1.6          0.4     0
27            5.2          3.5           1.5          0.2     0
28            5.2          3.4           1.4          0.2     0
29            4.7          3.2           1.6          0.2     0
..            ...          ...           ...          ...   ...
120           6.9          3.2           5.7          2.3     2
121           5.6          2.8           4.9          2.0     2
122           7.7          2.8           6.7          2.0     2
123           6.3          2.7           4.9          1.8     2
124           6.7          3.3           5.7          2.1     2
125           7.2          3.2           6.0          1.8     2
126           6.2          2.8           4.8          1.8     2
127           6.1          3.0           4.9          1.8     2
128           6.4          2.8           5.6          2.1     2
129           7.2          3.0           5.8          1.6     2
130           7.4          2.8           6.1          1.9     2
131           7.9          3.8           6.4          2.0     2
132           6.4          2.8           5.6          2.2     2
133           6.3          2.8           5.1          1.5     2
134           6.1          2.6           5.6          1.4     2
135           7.7          3.0           6.1          2.3     2
136           6.3          3.4           5.6          2.4     2
137           6.4          3.1           5.5          1.8     2
138           6.0          3.0           4.8          1.8     2
139           6.9          3.1           5.4          2.1     2
140           6.7          3.1           5.6          2.4     2
141           6.9          3.1           5.1          2.3     2
142           5.8          2.7           5.1          1.9     2
143           6.8          3.2           5.9          2.3     2
144           6.7          3.3           5.7          2.5     2
145           6.7          3.0           5.2          2.3     2
146           6.3          2.5           5.0          1.9     2
147           6.5          3.0           5.2          2.0     2
148           6.2          3.4           5.4          2.3     2
149           5.9          3.0           5.1          1.8     2

[150 rows x 5 columns]

In [108]:
y

iris
0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
..    ...
120     2
121     2
122     2
123     2
124     2
125     2
126     2
127     2
128     2
129     2
130     2
131     2
132     2
133     2
134     2
135     2
136     2
137     2
138     2
139     2
140     2
141     2
142     2
143     2
144     2
145     2
146     2
147     2
148     2
149     2

[150 rows x 1 columns]

In [109]:
trainnX,testnX,trainy,testy=train_test_split(nX,y,test_size=0.2,random_state=4)

In [110]:
lda=LDA(n_components=3)
trainnX=lda.fit_transform(trainnX,trainy)
testnX=lda.transform(testnX)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [111]:
dec=DecisionTreeClassifier()
model=dec.fit(trainnX,trainy)


In [112]:
preds=model.predict(testnX)

In [113]:
preds

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2])

In [114]:
model.score(trainnX,trainy)

1.0

In [115]:
cm=confusion_matrix(testy,preds)
print(cm)

[[16  0  0]
 [ 0  4  1]
 [ 0  1  8]]
