In [1]:
print("Start")

Start


In [46]:
import numpy as np

In [47]:
arr1=np.array([25,56,12,85,34,75])
arr2=np.array([42,3,86,32,856,46])


In [48]:
Narr=np.random.randint(0,1000,size=len(arr1))

In [49]:
Narr

array([867, 277, 721, 845, 911, 964])

In [50]:
arr1=np.array(arr1,dtype=complex)

In [51]:
arr1

array([25.+0.j, 56.+0.j, 12.+0.j, 85.+0.j, 34.+0.j, 75.+0.j])

In [73]:
arr1_mat=arr1.reshape((2,3))
arr2_mat=np.reshape(arr2,(2,3))

In [74]:
arr1_mat

array([[25.+0.j, 56.+0.j, 12.+0.j],
       [85.+0.j, 34.+0.j, 75.+0.j]])

In [75]:
((arr1_mat*arr1_mat) - (arr2_mat*arr2_mat))/(arr1_mat-arr2_mat)

array([[ 67.-0.j,  59.+0.j,  98.-0.j],
       [117.+0.j, 890.-0.j, 121.+0.j]])

In [155]:
arr = np.arange(4)
print(arr)
s=arr.reshape(2,2) 
print(s)

[0 1 2 3]
[[0 1]
 [2 3]]


In [88]:
v=np.eye(N=4)

In [179]:
v

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [175]:
v*np.array([0,4,5,6])

array([[0., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 6.]])

In [99]:
arr=np.arange(11)

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr[7:10]*=-1

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6, -7, -8, -9, 10])

In [104]:

mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 

In [105]:
mat

array([['abc', 'A'],
       ['def', 'B'],
       ['ghi', 'C'],
       ['jkl', 'D']], dtype='<U3')

In [106]:
mat[0]

array(['abc', 'A'], dtype='<U3')

In [107]:
mat[0][0]

'abc'

In [198]:
import pandas as pd
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
mat

array([[ 1, 21,  3],
       [ 5,  4,  2],
       [56, 12,  4]])

In [211]:
mat[mat[:,1].argsort()]

array([[ 5,  4,  2],
       [56, 12,  4],
       [ 1, 21,  3]])

In [212]:

mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 

In [213]:
for i in mat:
    print(i)
l1=[]

['abc' 'A']
['def' 'B']
['ghi' 'C']
['jkl' 'D']


In [214]:
for i in range(0,len(mat)):
    for j in range(0,len(mat[i])):
        if(mat[i][0]==arr[i]): 
            l1.append(mat[i][1]) 
print(list(set(l1)))

['C', 'A']


In [215]:
import numpy as np

n1=np.eye(4,dtype=int)

n1=np.reshape(n1,(16,))

n1=np.insert(n1,0,0)
n1=np.delete(n1,16)
n1=n1.reshape(4,4) 
n1*np.array([0,4,5,6])

array([[0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6],
       [0, 0, 0, 0]])

In [221]:
import numpy as np
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])


In [224]:
-(np.partition(-arr,4))

array([590,  90,  50,  45,  24,  13,  14,  16,  13,   0])